# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-22.04'

steps:
- task: UseNode@1
  inputs:
    version: '16.x'
  displayName: 'Use Node.js 16'

- script: |
    node -v
    npm -v
  displayName: 'Check Node and npm'

- script: |
    rm -rf node_modules package-lock.json
    npm cache clean --force
    npm install --legacy-peer-deps
  displayName: 'Install Dependencies'

- script: |
    CI=false npm run build -- --openssl-legacy-provider
  displayName: 'Build React App'
  continueOnError: false