# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'

- script: |
    node -v
    npm install
  displayName: 'Install packages'

- script: |
    export NODE_OPTIONS=--openssl-legacy-provider
    CI=false npm run build
  displayName: 'Build React App'